services:

    #
    # Event Listeners
    #
    beloop.event_listener.send_password_remember_email:
        class: Beloop\Web\UserBundle\EventListener\SendPasswordRememberEmailEventListener
        parent: beloop.abstract_email_sender_event_listener
        calls:
            - [setTranslator, ['@translator']]
        tags:
            - { name: kernel.event_listener, event: password.remember, method: sendPasswordRememberEmail }

    beloop.event_listener.user_locale_listener:
        class: Beloop\Web\UserBundle\EventListener\UserLocaleListener
        arguments: ['@session', '%kernel.default_locale%']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
            - { name: kernel.event_subscriber }