services:

    #
    # Form Types
    #
    beloop.form_type.login:
        class: Beloop\Web\UserBundle\Form\Type\LoginType
        arguments:
            - "@router"
        tags:
            - { name: form.type }

    beloop.form_type.password_update:
        class: Beloop\Web\UserBundle\Form\Type\UserPasswordType
        arguments:
            - "@router"
        tags:
            - { name: form.type }