security:
    access_control:

        # admin
        admin_password_area:
            path: ^/%beloop_admin_prefix%/password.*
            roles: IS_AUTHENTICATED_ANONYMOUSLY

        admin_public_area:
            path: ^/%beloop_admin_prefix%/.*
            roles: ROLE_ADMIN

        # web
        password_area:
            path: ^/password/.*
            roles: IS_AUTHENTICATED_ANONYMOUSLY

        register_area:
            path: ^/register/.*
            roles: IS_AUTHENTICATED_ANONYMOUSLY

        public_area:
            path: ^/.+
            roles: ROLE_DEMO

        login_area:
            path: ^/
            roles: IS_AUTHENTICATED_ANONYMOUSLY
