security:
    access_control:

        # admin
        admin_password_area:
            path: ^/%beloop_admin_prefix%/password.*
            roles: IS_AUTHENTICATED_ANONYMOUSLY

        admin_public_area:
            path: ^/%beloop_admin_prefix%/.*
            roles: ROLE_ADMIN

        # web
        public_area:
            path: ^/.+
            roles: ROLE_USER

        login_area:
            path: ^/
            roles: IS_AUTHENTICATED_ANONYMOUSLY
