name: beloop-web

type: php:7.2

runtime:
    extensions:
        - apcu
        - mbstring

build:
    flavor: none

web:
    locations:
        "/":
            root: "web"
            expires: 1h
            passthru: "/app.php"

disk: 2048

mounts:
    "/app/config": { source: local, source_path: app_config }
    "/bin": { source: local, source_path: bin }
    "/var": { source: local, source_path: var }
    "/web": { source: local, source_path: web }

relationships:
    database: "beloopdb:admin"
    analytics: "beloopdb:analytics"

hooks:
    build: |
        set -x -e
        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        (>&2 symfony-build)
        mkdir -p tmp/app/config && mv app/config/* tmp/app/config/
        # Build production assets
        (>&2 SYMFONY_ENV=prod bin/console assetic:dump --env=prod --no-debug)
        mkdir -p tmp/bin && mv bin/* tmp/bin/
        mkdir -p tmp/web && mv web/* tmp/web/
    deploy: |
        set -xeuo pipefail
        (>&2 mkdir -p app/config)
        (>&2 cp -R tmp/app/config/* app/config/)
        (>&2 mkdir -p bin)
        (>&2 cp -R tmp/bin/* bin/)
        (>&2 mkdir -p web)
        (>&2 cp -R tmp/web/* web/)
        # Recreate the cache with correct environment variables
        (>&2 rm -rf var/cache/*)
        (>&2 SYMFONY_ENV=prod SYMFONY_DEBUG=0 composer run post-install-cmd)
        (>&2 SYMFONY_ENV=prod SYMFONY_DEBUG=0 php app/console cache:clear)
