imports:
    - { resource: security/security.yml }
    - { resource: services.yml }

# Default parameter values
parameters:
    locale: en
    beloop_admin_prefix:  '%env(BELOOP_ADMIN_PREFIX)%'
    squarespace_password: '%env(SQUARESPACE_PASSWORD)%'
    typeform_api_key:     '%env(TYPEFORM_API_KEY)%'

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%env(APP_SECRET)%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enabled: true, enable_annotations: false }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                server_version: '10.2'
                url:     "%env(DATABASE_URL)%"
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci
            analytics:
                driver:   pdo_mysql
                server_version: '10.2'
                url:     "%env(ANALYTICS_URL)%"
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                auto_mapping: false
                metadata_cache_driver: array
                query_cache_driver: array
                result_cache_driver: array
            analytics:
                connection: analytics
                auto_mapping: false
                metadata_cache_driver: array
                query_cache_driver: array
                result_cache_driver: array

# Swiftmailer Configuration
swiftmailer:
    url:   "%env(MAILER_URL)%"
    spool: { type: memory }

guzzle:
    clients:
        api_squarespace:
            base_url: "https://dyb-courses.squarespace.com"
            headers:
                Accept: "*/*"
                Host: "dyb-courses.squarespace.com"
        api_typeform:
            base_url: "https://aialahernando.typeform.com/v1/form/"
            headers:
                Accept: "*/*"
                Host: "aialahernando.typeform.com"

vich_uploader:
    db_driver: orm

    metadata:
        directories:
            - { path: "@BeloopCourseBundle/Resources/config/vich_uploader", namespace_prefix: Beloop\Component\Course\Entity }
            - { path: "@BeloopUserBundle/Resources/config/vich_uploader", namespace_prefix: Beloop\Component\User\Entity }
            - { path: "@BeloopInstagramBundle/Resources/config/vich_uploader", namespace_prefix: Beloop\Component\Instagram\Entity }

    mappings:
        course_image:
            uri_prefix:         /images/course
            upload_destination: %kernel.root_dir%/../web/images/course
            namer:              vich_uploader.namer_uniqid

        user_avatar:
            uri_prefix:         /images/avatar
            upload_destination: %kernel.root_dir%/../web/images/avatar
            namer:              vich_uploader.namer_uniqid

        instagram:
            uri_prefix:         /images/instagram
            upload_destination: %kernel.root_dir%/../web/images/instagram
            namer:              vich_uploader.namer_uniqid

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        instagram_thumb:
            quality: 80
            filters:
                relative_resize: { widen: 600 }
        profile_thumb:
            quality: 80
            filters:
                thumbnail: { size: [150, 150], mode: outbound }
        profile_mini_thumb:
            quality: 100
            filters:
                thumbnail: { size: [43, 43], mode: outbound }
        course_thumb:
            quality: 80
            filters:
                relative_resize: { widen: 700 }

beloop_squarespace:
    authorization:
        password: "%squarespace_password%"
