services:

    # Form Types

    beloop_admin.form_type.user:
        class: Beloop\Admin\UserBundle\Form\Type\UserType
        calls:
            - [setFactory, ["@beloop.factory.user"]]
        tags:
            - { name: form.type }
