parameters:
    env(DATABASE_URL): "mysql://db_user:db_password@127.0.0.1:3306/db_name"

beloopdb:
    type: mysql:10.2
    disk: 2048
    configuration:
        schemas:
            - default
            - analytics
        endpoints:
            admin:
                default_schema: default
                privileges:
                    default: admin
                    legacy: admin
