beloopdb:
    type: mysql:10.2
    disk: 1024
    configuration:
        schemas:
            - default
            - analytics
        endpoints:
            admin:
                default_schema: default
                privileges:
                    default: admin
                    analytics: admin
            analytics:
                default_schema: analytics
                privileges:
                    analytics: rw
