services:

    #
    # Form Types
    #
    beloop.form_type.instagram:
        class: Beloop\Web\InstagramBundle\Form\Type\InstagramType
        arguments:
            - '@router'
            - '@beloop.wrapper.user'
        calls:
            - [setFactory, ["@beloop.factory.instagram"]]
        tags:
            - { name: form.type }