#
# Web routes
#
dashboard_routes:
    resource: "@DashboardBundle/Resources/config/routing.yml"

my_courses_routes:
    resource: "@CourseBundle/Resources/config/routing.yml"

squarespace_routes:
    resource: "@BeloopSquarespaceBundle/Resources/config/routing.yml"

typeform_routes:
    resource: "@BeloopTypeformBundle/Resources/config/routing.yml"