#
# Admin routes
#

admin_common:
    resource: "@AdminCommonBundle/Resources/config/routing.yml"

#admin_course:
#    resource: "@AdminCourseBundle/Resources/config/routing.yml"
#
#admin_user:
#    resource: "@AdminUserBundle/Resources/config/routing.yml"
